services:
  - type: web
    name: jayaraman-k-portfolio
    env: static
    buildCommand: npm install
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html